# @package _global_

# close to exp1 but + random interpolation (to see how it affects performance)
# for fair comparison will run using 1 GPU only

defaults:
  - /base@_here_

model:
  _target_: pytorch_tools.models.resnet50

log:
  exp_name: r50_rand_interp

# use larger weight decay because of label smoothing
optim:
  weight_decay: 3e-5

# use label smoothing
criterion:
  smoothing: 0.1

loader:
  image_size: 224
  batch_size: 256
  random_interpolation: True

run:
  stages:
    - {start: 0, end: 8, lr: [0.001, 1.0]}
    - {start: 8, end: 90, lr: [1.0, 0], lr_mode: cos}
