# @package _global_

# should be close to exp4.

defaults:
  - /base@_here_

model:
  _target_: pytorch_tools.models.resnet50

log:
  exp_name: r50_adamw_repeat_ortho-init
  histogram: True
  print_model: True

# first run of this experiment
optim:
  _target_: torch.optim._multi_tensor.AdamW
  weight_decay: 2e-2 # 0.02 * 0.002 ~= 4e-5
  lr: 0
  # eps: 1e-5

# use label smoothing
criterion:
  smoothing: 0.1

loader:
  image_size: 224
  batch_size: 192
  # color augmentations to prevent overfit
  color_twist_prob: 0.3

run:
  stages:
    - {start: 0, end: 8, lr: [0, 0.002]}
    - {start: 8, end: 90, lr: [0.002, 0], lr_mode: cos}

  extra_callbacks:
    # not sure it doesn't make it worse so disable for now
    - _target_: src.callbacks.OrthoInitClb

    - _target_: src.callbacks.GradDistributionTB
      log_every: 250

init_gamma: 1.7 # proper weight init
