# @package _global_

# similar to exp 62_4.vgg-cmodel_s2d_4
# VGG using CModel
# + HardSwish 
# + AvgPool2d instead of MaxPool2d
# + space2depth block size 4
# + post-normalization
# + BN -> FRN v1 (for now with bias on, despite the fact we don't subtract mean)

# good news - it works same as BN (really-really close in terms of both train and val accuracy), FRN even slightly better on val loss
# bad news - it's much slower, because BN is very well implemented and FRN not. 22m instead of 15m, this is not acceptable
# killed exp after 13 epochs

defaults:
  - /base@_here_
  
log:
  exp_name: vgg-cmodel_sd4_frn
  histogram: True
  print_model: True

model:
  _target_: sota_imagenet.model.CModel
  extra_kwargs:
    ReLU:
      inplace: True

  layer_config:
    # VGG16: [64, 64, 'M', 128, 128, 'M', 256, 256, 256, 'M', 512, 512, 512, 'M', 512, 512, 512, 'M'],
    # 1
    - [-1, 1, pt.modules.SpaceToDepth, 4]
    - [-1, 1, conv3x3, [48, 64]]
    - [-1, 1, nn.Hardswish]
    - [-1, 1, FRNv1, 64]
    # 2
    - [-1, 1, conv3x3, [64, 64]]
    - [-1, 1, nn.Hardswish]
    - [-1, 1, FRNv1, 64]
    # - [-1, 1, nn.AvgPool2d, [2, 2]] # os=2
    # 3
    - [-1, 1, conv3x3, [64, 128]]
    - [-1, 1, nn.Hardswish]
    - [-1, 1, FRNv1, 128]
    # 4`
    - [-1, 1, conv3x3, [128, 128]]
    - [-1, 1, nn.Hardswish]
    - [-1, 1, FRNv1, 128]
    # - [-1, 1, nn.AvgPool2d, [2, 2]] # os=4
    # 5
    - [-1, 1, conv3x3, [128, 256]]
    - [-1, 1, nn.Hardswish]
    - [-1, 1, FRNv1, 256]
    # 6
    - [-1, 1, conv3x3, [256, 256]]
    - [-1, 1, nn.Hardswish]
    - [-1, 1, FRNv1, 256]
    # 7
    - [-1, 1, conv3x3, [256, 256]]
    - [-1, 1, nn.Hardswish]
    - [-1, 1, FRNv1, 256]
    - [-1, 1, nn.AvgPool2d, [2, 2]] # os=8
    # 8
    - [-1, 1, conv3x3, [256, 512]]
    - [-1, 1, nn.Hardswish]
    - [-1, 1, FRNv1, 512]
    # 9
    - [-1, 1, conv3x3, [512, 512]]
    - [-1, 1, nn.Hardswish]
    - [-1, 1, FRNv1, 512]
    # 10
    - [-1, 1, conv3x3, [512, 512]]
    - [-1, 1, nn.Hardswish]
    - [-1, 1, FRNv1, 512]
    - [-1, 1, nn.AvgPool2d, [2, 2]] # os=16
    # 11
    - [-1, 1, conv3x3, [512, 512]]
    - [-1, 1, nn.Hardswish]
    - [-1, 1, FRNv1, 512]
    # 12
    - [-1, 1, conv3x3, [512, 512]]
    - [-1, 1, nn.Hardswish]
    - [-1, 1, FRNv1, 512]
    # 13
    - [-1, 1, conv3x3, [512, 512]]
    - [-1, 1, nn.Hardswish]
    - [-1, 1, FRNv1, 512]
    
    # in original VGG they have FC(512 * 7 * 7 -> 4096) here but i'm using GAP + FC(512 -> 4096)
    - [-1, 1, pt.modules.FastGlobalAvgPool2d, [], {flatten: True}]
    - [-1, 1, nn.Linear, [512, 4096]]
    - [-1, 1, nn.Hardswish]
    - [-1, 1, nn.Linear, [4096, 4096]]
    - [-1, 1, nn.Hardswish]
    - [-1, 1, nn.Linear, [4096, 1000]]

# using default SGD
optim:
  _target_: torch.optim._multi_tensor.SGD
  momentum: 0.9
  weight_decay: 3e-5
  lr: 0

# use label smoothing
criterion:
  smoothing: 0.1

loader:
  image_size: 224
  batch_size: 224
  blur_prob: 0.2
  gray_prob: 0.2
  color_twist_prob: 0.4
  re_prob: 0.3

val_loader:
  image_size: 288 # to test on the same resolution as timm

run:
  stages:
    # SGD requires warmup
    - {start: 0, end: 3, lr: [0.001, 0.1]}
    - {start: 3, end: 90, lr: [0.1, 0], lr_mode: cos}

  extra_callbacks:
    - _target_: sota_imagenet.callbacks.CutmixMixup
      cutmix_alpha: 1.0
      mixup_alpha: 0.2
      prob: 1.0

filter_from_wd: [gain] # filter bias and gain from wd
# leaving gain param to apply proper init for the model
init_gamma: 1.7 # value from NFNet paper for SiLU activation
