# @package _global_

# same as best exp33 and exp56
# + s2d
# here the number of modifications is much smaller 

defaults:
  - /base@_here_
  
log:
  exp_name: nf_s2d4_small-mod
  histogram: True
  print_model: True

model:
  _target_: sota_imagenet.model.CModel
  extra_kwargs:
    ConvActBlock:
      activation: "'swish_hard'"
      # activation: "'selu'"
      conv_kwargs:
        gamma: "${init_gamma}"
        gain_init: 0.1
        n_heads: 1
    NormFreeBlockTimm:
      activation: "'swish_hard'"
      groups_width: 64
      alpha: 0.2
      conv_kwargs:
        gamma: "${init_gamma}"
      attention_type: "'eca9'"
      keep_prob: 0.85 # will set the same for each block and then patch to linearly increase
      regnet_attention: True
    VarEMA:
      use: False
    scaled_conv3x3: {gamma: "${init_gamma}"}
    torch.nn.SiLU: {inplace: True}

  layer_config:
    # residual starts from the very firt layer. 
    # larger gain during first channel increase for faster convergence during training
    - [-1, 1, pt.modules.SpaceToDepth, 4]
    - [-1, 1, ConvActBlock, [48, 64]]
    - [-1, 1, ConvActBlock, [64, 64]]
    - [-1, 1, VarEMA, 64]
      # stage 1
    - [-1, 4, "ConvActBlock", [64, 64]]
      # stage 2
    - [-1, 1, VarEMA, 64]
    - [-1, 1, "ConvActBlock", [64, 128], {stride: 2}]
    - [-1, 1, VarEMA, 128]
    - [-1, 5, "ConvActBlock", [128, 128], {groups_width: 64}]
      # stage 3
    - [-1, 1, VarEMA, 128]
    - [-1, 1, pt.modules.BlurPool, 128]
    - [-1, 1, VarEMA, 128]
    - [-1, 1, NormFreeBlockTimm, [128, 768, 384]]
    - [-1, 6, NormFreeBlockTimm, [768, 768, 384]]
    - [-1, 1, VarEMA, 768]
      # stage 4
    - [-1, 1, pt.modules.BlurPool, 768]
    - [-1, 1, VarEMA, 768]
    - [-1, 5, NormFreeBlockTimm, [768, 768, 384]]
      # head
    - [-1, 1, scaled_conv1x1, [768, 2304], {gamma: "${init_gamma}"}]
    - [-1, 1, torch.nn.SiLU]
    - [-1, 1, pt.modules.FastGlobalAvgPool2d, [], {flatten: True}]
    - [-1, 1, torch.nn.Dropout, [0.2]]
    - [-1, 1, nn.Linear, [2304, 1000]]

# using default SGD
optim:
  _target_: torch.optim._multi_tensor.SGD
  momentum: 0.9
  weight_decay: 3e-5
  lr: 0

# optim:
#   # in PyTorch implementation weight decay is lr * wd, so 0.1 == 1e-4 as in AdamW paper
#   _target_: src.optimizers.AdamLayerwise
#   weight_decay: 1e-2
#   betas: [0.9, 0.995]
#   lr: 0

# use label smoothing
criterion:
  smoothing: 0.1

loader:
  image_size: 224
  batch_size: 224
  blur_prob: 0.2
  gray_prob: 0.2
  color_twist_prob: 0.4
  re_prob: 0.3

val_loader:
  image_size: 288 # to test on the same resolution as timm

run:
  stages:
    # SGD requires warmup
    - {start: 0, end: 90, lr: [0.3, 0], lr_mode: cos}

  extra_callbacks:
    - _target_: sota_imagenet.callbacks.CutmixMixup
      cutmix_alpha: 1.0
      mixup_alpha: 0.2
      prob: 1.0

filter_from_wd: [gain] # filter bias and gain from wd
init_gamma: 2 # larger value to compensate for variance reduction after BlurPool
