# @package _global_

# close to exp77
# but using UFO in OS=16 instead of XCA. it's actually almost the same but with norm instead of softmax
# like run2 of 77. 25.4M params. slightly faster training. like 12.15m per epoch instead of 12.5m

# TODO: try swapping norm dimensions
# run1 was with -1, -2, run2 was with -2, -1, started with slightly higher loss, but then recovered
# run2 failed after 35 epochs with nan. not sure what caused it. let's try using -1, -2 again

# TOOD: maybe explosion could be avoided by using scaled post-projection conv1x1? 


defaults:
  - /base@_here_
  
log:
  exp_name: non-deeps_ufo_dim-1dim-2

  histogram: True
  print_model: True

model:
  _target_: sota_imagenet.model.CModel
  extra_kwargs:
    NonDeepBlock:
      norm: nn.BatchNorm2d
      scaled: True

  layer_config:
    - [-1, 1, pt.modules.SpaceToDepth, 4] # os=4
    # residual starts from the very first layer
    - [-1, 1, NonDeepBlock, [48, 128]]
    - [-1, 1, NonDeepBlock, [128, 128]]
    - [-1, 1, nn.AvgPool2d, [2, 2]] # os=8
    - [-1, 1, NonDeepBlock, [128, 256]]
    - [-1, 2, NonDeepBlock, [256, 256]]
    - [-1, 1, nn.AvgPool2d, [2, 2]] # os=16
    - [-1, 1, NonDeepBlock, [256, 384]]
    - [-1, 8, NonDeepBlock, [384, 384], {ufo_kwargs: {residual: True, last_proj: False}}]
    - [-1, 1, pt.modules.FastGlobalAvgPool2d, [], {flatten: True}]
    - [-1, 1, nn.Linear, [384, 2048]]
    - [-1, 1, nn.Hardswish]
    - [-1, 1, nn.Linear, [2048, 2048]]
    - [-1, 1, nn.Hardswish]
    - [-1, 1, nn.Linear, [2048, 1000]]

# using default SGD
optim:
  _target_: torch.optim._multi_tensor.SGD
  momentum: 0.9
  weight_decay: 3e-5
  lr: 0

# optim:
#   # in PyTorch implementation weight decay is lr * wd, so 0.1 == 1e-4 as in AdamW paper
#   _target_: src.optimizers.AdamLayerwise
#   weight_decay: 1e-2
#   betas: [0.9, 0.995]
#   lr: 0

# use label smoothing
criterion:
  smoothing: 0.1

loader:
  image_size: 224
  batch_size: 224
  blur_prob: 0.2
  gray_prob: 0.2
  color_twist_prob: 0.4
  re_prob: 0.3

val_loader:
  image_size: 288 # to test on the same resolution as timm

run:
  stages:
    # SGD requires warmup
    - {start: 0, end: 3, lr: [0.001, 0.1]}
    - {start: 3, end: 90, lr: [0.1, 0], lr_mode: cos}

  extra_callbacks:
    - _target_: sota_imagenet.callbacks.CutmixMixup
      cutmix_alpha: 1.0
      mixup_alpha: 0.2
      prob: 1.0

filter_from_wd: [gain] # filter bias and gain from wd
init_gamma: 1.7 # larger value to compensate for variance reduction after BlurPool
